@php
    $temp1 = base64_decode('SW5hbGlkIFByb2R1Y3QgTGljZW5zZQ==');
    $temp2 = base64_decode('aHR0cHM6Ly93d3cuamFkZXNkZXYuY29tLm5nL3N1cHBvcnQ=');
    $domain = request()->getHost() ?? '';
@endphp
@php
    echo base64_decode(
        'CjwhRE9DVFlQRSBodG1sPgo8aHRtbCBsYW5nPSJlbiI+Cgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4=',
    );
@endphp

<title>{{ $temp1 }}</title>
@php
    echo base64_decode(
        'PHN0eWxlPgogICAgICAgIDpyb290IHsKICAgICAgICAgICAgLS1wcmltYXJ5LWNvbG9yOiAjNEE2Q0ZBOwogICAgICAgICAgICAtLWRhbmdlci1jb2xvcjogI0RDMzU0NTsKICAgICAgICAgICAgLS1kYXJrLWNvbG9yOiAjMjEyNTI5OwogICAgICAgICAgICAtLWxpZ2h0LWNvbG9yOiAjRjhGOUZBOwogICAgICAgICAgICAtLWdyYXktY29sb3I6ICM2Qzc1N0Q7CiAgICAgICAgICAgIC0tYm9yZGVyLWNvbG9yOiAjREVFMkU2OwogICAgICAgIH0KCiAgICAgICAgYm9keSB7CiAgICAgICAgICAgIGZvbnQtZmFtaWx5OiAnU2Vnb2UgVUknLCBUYWhvbWEsIEdlbmV2YSwgVmVyZGFuYSwgc2Fucy1zZXJpZjsKICAgICAgICAgICAgbGluZS1oZWlnaHQ6IDEuNjsKICAgICAgICAgICAgY29sb3I6IHZhcigtLWRhcmstY29sb3IpOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjVmN2ZiOwogICAgICAgICAgICBtYXJnaW46IDA7CiAgICAgICAgICAgIHBhZGRpbmc6IDA7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgICAgICAgICBtaW4taGVpZ2h0OiAxMDB2aDsKICAgICAgICB9CgogICAgICAgIC5jb250YWluZXIgewogICAgICAgICAgICBtYXgtd2lkdGg6IDgwMHB4OwogICAgICAgICAgICB3aWR0aDogMTAwJTsKICAgICAgICAgICAgbWFyZ2luOiAyMHB4OwogICAgICAgICAgICBib3JkZXItcmFkaXVzOiAxMHB4OwogICAgICAgICAgICBib3gtc2hhZG93OiAwIDRweCAyMHB4IHJnYmEoMCwgMCwgMCwgMC4wOCk7CiAgICAgICAgICAgIGJhY2tncm91bmQtY29sb3I6IHdoaXRlOwogICAgICAgICAgICBvdmVyZmxvdzogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmhlYWRlciB7CiAgICAgICAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWRhbmdlci1jb2xvcik7CiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTsKICAgICAgICAgICAgcGFkZGluZzogMjBweDsKICAgICAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRlbnQgewogICAgICAgICAgICBwYWRkaW5nOiAzMHB4OwogICAgICAgIH0KCgogICAgICAgIC5hY3Rpb24tYm94IHsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2Y4ZjlmYTsKICAgICAgICAgICAgYm9yZGVyLWxlZnQ6IDRweCBzb2xpZCB2YXIoLS1wcmltYXJ5LWNvbG9yKTsKICAgICAgICAgICAgcGFkZGluZzogMTVweDsKICAgICAgICAgICAgbWFyZ2luOiAyNXB4IDA7CiAgICAgICAgfQoKICAgICAgICAuYnRuIHsKICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1wcmltYXJ5LWNvbG9yKTsKICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgICAgIHBhZGRpbmc6IDEycHggMjRweDsKICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogNXB4OwogICAgICAgICAgICBmb250LXdlaWdodDogNTAwOwogICAgICAgICAgICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kLWNvbG9yIDAuM3M7CiAgICAgICAgfQoKICAgICAgICAuYnRuOmhvdmVyIHsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogIzNBNUNEQTsKICAgICAgICB9CgogICAgICAgIGgyIHsKICAgICAgICAgICAgbWFyZ2luLXRvcDogMDsKICAgICAgICB9CgogICAgICAgIC50ZXh0LWRhbmdlciB7CiAgICAgICAgICAgIGNvbG9yOiB2YXIoLS1kYW5nZXItY29sb3IpOwogICAgICAgIH0KCiAgICAgICAgLnN0ZXBzIHsKICAgICAgICAgICAgbGlzdC1zdHlsZS10eXBlOiBub25lOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBjb3VudGVyLXJlc2V0OiBzdGVwczsKICAgICAgICB9CgogICAgICAgIC5zdGVwcyBsaSB7CiAgICAgICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsKICAgICAgICAgICAgcGFkZGluZy1sZWZ0OiA1MHB4OwogICAgICAgICAgICBtYXJnaW4tYm90dG9tOiAyMHB4OwogICAgICAgICAgICBjb3VudGVyLWluY3JlbWVudDogc3RlcHM7CiAgICAgICAgfQoKICAgICAgICAuc3RlcHMgbGk6OmJlZm9yZSB7CiAgICAgICAgICAgIGNvbnRlbnQ6IGNvdW50ZXIoc3RlcHMpOwogICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICAgICAgICAgIGxlZnQ6IDA7CiAgICAgICAgICAgIHRvcDogMDsKICAgICAgICAgICAgd2lkdGg6IDMwcHg7CiAgICAgICAgICAgIGhlaWdodDogMzBweDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tcHJpbWFyeS1jb2xvcik7CiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTsKICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogNTAlOwogICAgICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICAgICAgICAgICAgZm9udC13ZWlnaHQ6IGJvbGQ7CiAgICAgICAgfQogICAgPC9zdHlsZT4=',
    );
@endphp
</head>

<body>
    <div class="container">
        <div class="header">
            <h2>⚠️ {{ $temp1 }}</h2>
        </div>
        <div class="content">

            {!! base64_decode(
                'PGgzPkFjY2VzcyBSZXN0cmljdGVkPC9oMz4KICAgICAgICAgICAgPHA+IFRvIHVzZSB0aGlzIHNjcmlwdCwgS2luZGx5IHB1cmNoYXNlIGZyb20gdGhlIHJpZ2h0IHNvdXJjZSBvciBwcm92aWRlIHlvdXIgbGljZW5zZSBjb2RlIG9uIHRoaXMgZG9tYWluLgogICAgICAgICAgICA8L3A+',
            ) !!}
            <p> <strong>{{ $domain }}</strong></p>

            @php
                echo base64_decode(
                    'CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgRW5zdXJlIHlvdSBoYXZlIG5vdCByZWFjaCB0aGUgbWF4aW11bSBhbGxvd2VkIGRvbWFpbiBvbiB5b3VyIGxpY2Vuc2UgY29kZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD5FbnN1cmUgdGhhdCB0aGlzIGlzIGEgdmFsaWQgZG9tYWluIGZvciB5b3VyIGxpY2Vuc2UgY29kZS48L3A+',
                );

                echo base64_decode(
                    'PGRpdiBjbGFzcz0iYWN0aW9uLWJveCI+CiAgICAgICAgICAgICAgICA8aDQ+SG93IHRvIEZpeCBUaGlzIElzc3VlOjwvaDQ+CiAgICAgICAgICAgICAgICA8dWwgY2xhc3M9InN0ZXBzIj4KICAgICAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgICAgIDxzdHJvbmc+VmVyaWZ5IHlvdXIgQUNDRVNTX0tFWTwvc3Ryb25nPjxicj4KICAgICAgICAgICAgICAgICAgICAgICAgTWFrZSBzdXJlIHlvdXIgPGNvZGU+QUNDRVNTX0tFWTwvY29kZT4gaXMgc2V0IGNvcnJlY3RseSBhbmQgaXMgdmFsaWQuCiAgICAgICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgICAgIDxzdHJvbmc+Q29udGFjdCBzdXBwb3J0PC9zdHJvbmc+PGJyPgogICAgICAgICAgICAgICAgICAgICAgICBJZiB5b3UgY29udGludWUgZXhwZXJpZW5jaW5nIGlzc3VlcywgcGxlYXNlIHJlYWNoIG91dCB0byBvdXIgc3VwcG9ydCB0ZWFtLgogICAgICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8L3VsPgogICAgPC9kaXY+',
                );
            @endphp

            <div
                @php echo base64_decode('Y2xhc3M9InRleHQtY2VudGVyIiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyBtYXJnaW4tdG9wOiAzMHB4OyI='); @endphp>
                <a href="{{ $temp2 }}" class="btn">{{ base64_decode('Q29udGFjdCBTdXBwb3J0') }}</a>
            </div>
        </div>

    </div>
</body>

</html>
